apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - port: 3000
  type: LoadBalancer
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: iteam1337/safespring-hello-world
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
    - host: hello-world.safespring
      http:
        paths:
          - backend:
              serviceName: hello-world
              servicePort: 3000
